### ISSUE TITLE
Support redirect URLs

### ISSUE THREAD

**Issue by monicachew** [mozilla-services/shavar#28]
Right now the chunk data is being sent back inline. @tblow says that if we can offload this traffic to a CDN the costs will be cheaper.

Search for "redirect" on https://developers.google.com/safe-browsing/developers_guide_v2.

**Comment by fmarier** [comment]
Note: the redirect URLs currently have to be schemeless (like in the example from the spec, but unlike the grammar) because of [this client code](https://dxr.mozilla.org/mozilla-central/rev/29b2df16e961fbe9a379362ecba6f888d1754bc3/toolkit/components/url-classifier/nsUrlClassifierStreamUpdater.cpp#268-272).

**Comment by monicachew** [comment]
Well, also to match what Google sends back.

**Comment by fmarier** [comment]
This is live in production.
